name: Reusable - Validate (plugin)

on:
  workflow_call:
    inputs:
      hacs_category:
        type: string
        required: false
        default: "plugin"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@vmain
        with:
          category: ${{ inputs.hacs_category }}
